name: Generate Report 2
on:
  pull_request:
    types:
      - closed

jobs:
  generate_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate Report
        run: |
          base_branch="${{ github.event.pull_request.base.ref }}"
          head_branch="${{ github.event.pull_request.head.ref }}"
          echo "Base Branch: $base_branch"
          echo "Head Branch: $head_branch"
          echo "Timestamp: $(date)"
          git fetch origin $base_branch
          git fetch origin $head_branch
          git diff origin/$base_branch..origin/$head_branch > report.txt

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: diff-report
          path: report.txt
