name: Generate Report
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - 'main'

jobs:
  generate_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Report
        run: |
          base_branch="${{ github.event.pull_request.base.ref }}"
          head_branch="${{ github.event.pull_request.head.ref }}"

          echo "Base Branch: $base_branch"
          echo "Head Branch: $head_branch"
          echo "Timestamp: $(date)"

          git diff $base_branch..$head_branch
